vich_uploader:
  db_driver: orm
  
  mappings:
    deals_images:
      uri_prefix: '%app.path.deals_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.deals_images%'
    users_images:
      uri_prefix: '%app.path.users_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.users_images%'
