version: '3'
services:
    apache:
        build: .docker/apache
        container_name: lpa_sf4_apache
        ports:
          - 8081:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - lpa-sf4-files:/var/www/lpa_sf4:nocopy
          - .docker/data/apache:/var/log/apache2
        environment:
          PHP_IDE_CONFIG: serverName=lpa_sf4.docker
        depends_on:
          - php

    php:
        build: .docker/php
        container_name: lpa_sf4_php
        volumes:
          - lpa-sf4-files:/var/www/lpa_sf4:nocopy
        environment:
          - mailcatcher_host=lpa_sf4_mailcatcher
        depends_on:
          - mailcatcher

    mailcatcher:
        container_name: lpa_sf4_mailcatcher
        restart: on-failure:10
        image: dockage/mailcatcher:0.7.1
        ports:
            - 1081:1080
            - 1026:1025

    mysql:
        image: mysql:5.7
        command: ['--default-authentication-plugin=mysql_native_password']
        container_name: lpa_sf4_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - "3310:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: lpa_sf4
            MYSQL_USER: lpa_sf4
            MYSQL_PASSWORD: lpa_sf4

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: lpa_sf4_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8090:80
        links:
            - mysql


volumes:
    lpa-sf4-files:
        external: true
